name: flaskenv
channels:
 - defaults
 - anaconda
 - conda-forge
dependencies:
 - flask
 - flask-sqlalchemy
 - flask-wtf
 - flask-mail
 - flask-migrate
 - flask-login
 - passlib[bcrypt]
 - bleach
 - python-dotenv
 - pyjwt
 - pymysql
 - pip